In [7]:
import numpy as np
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
print ("the shape is 2 rows and 3 columns",arr2.shape)

the shape is 2 rows and 3 columns (2, 3)


In [13]:
print(arr2[0][2])
print (arr2[0,2])
print(arr2[0,-1])
print(arr2[-1,0])


3
3
3
5


In [17]:
arr3 = np.array(['india','china','usa','mexico'])
print(arr3)

['india' 'china' 'usa' 'mexico']


In [19]:
arr3[1]

'china'

In [21]:
arr=np.arange(0,20,2)
print(arr)


[ 0  2  4  6  8 10 12 14 16 18]


In [33]:
arr=np.linspace(0,10,20)
print(arr)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [36]:
arr=np.random.rand(10)
print(arr)

[0.66835032 0.06081713 0.53033864 0.22007652 0.79653001 0.90224658
 0.64326826 0.71235562 0.41104702 0.41787366]


In [27]:
arr=np.random.rand(3,4)
print(arr)

[[0.06381179 0.879497   0.73332889 0.04928206]
 [0.44663663 0.71041208 0.42694473 0.8837078 ]
 [0.55167472 0.53877801 0.44263703 0.94723291]]


In [34]:
print(np.full((4,6),10))

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]


In [39]:
arr=[0,2,1]
print(np.repeat(arr,4))

[0 0 0 0 2 2 2 2 1 1 1 1]


In [40]:
arr=[0,1,2]
print(np.tile(arr,4))

[0 1 2 0 1 2 0 1 2 0 1 2]


In [49]:
identity_matrix=np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [54]:
identity_matrix=np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [46]:
arr=np.random.rand(5,5)
print(arr)

[[0.42534905 0.10751388 0.57143709 0.69226314 0.39243865]
 [0.82513964 0.7706335  0.37700475 0.63583092 0.65945468]
 [0.74342383 0.07594313 0.97641386 0.0945395  0.60852401]
 [0.22194938 0.76773587 0.89390799 0.37389823 0.50495834]
 [0.91550976 0.44963578 0.31405965 0.86094107 0.25655992]]


In [53]:
print(np.sum(arr,axis=0))

[3.13137164 2.17146217 3.13282334 2.65747287 2.42193559]


In [55]:
print(np.sum(arr,axis=1))


[2.18900181 3.26806349 2.49884433 2.76244981 2.79670618]


In [56]:
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))

0.5406026245422308
0.5714370890408094
0.2662039392886493
0.07086453729279489


In [71]:
arr=np.random.rand(5,5)
print(np.sort(arr,axis=1))

[[0.22421618 0.66129008 0.76567262 0.88457289 0.90063481]
 [0.16069508 0.47793121 0.73502187 0.74828049 0.99379187]
 [0.03416474 0.05199674 0.06509853 0.47592749 0.8189029 ]
 [0.03013754 0.0823901  0.28473872 0.71863531 0.78061379]
 [0.10448259 0.3937334  0.79072244 0.93757312 0.98714179]]


In [62]:
arr=np.array([4,5,6,7])

In [65]:
arr1=np.append(arr,8)
print(arr1)

[4 5 6 7 8]


In [66]:
arr2=np.append(arr,[9,10,11])
print(arr2)

[ 4  5  6  7  9 10 11]


In [68]:
arr2=np.array([4,5,6,7,9,10,11])
print(arr2)
print('\n')
arr5=np.delete(arr2,[1,4])
print(arr5)

[ 4  5  6  7  9 10 11]


[ 4  6  7 10 11]


In [82]:
arr1=np.array([[1,2,3,4],[1,2,3,4]])
arr2=np.array([[5,6,7,8],[5,6,7,8]])


In [76]:
cat=np.concatenate((arr1,arr2),axis=0)
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [77]:
cat=np.concatenate((arr1,arr2),axis=1)
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]
